steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
          [
              'build',
              '-t',
              'gcr.io/next-warehousing-solutions/github.com/jonathandsouza/next-warehousing-solutions-front-end:$SHORT_SHA',
              '.',
          ]
    - name: 'gcr.io/cloud-builders/docker'
      args:
          [
              'push',
              'gcr.io/next-warehousing-solutions/github.com/jonathandsouza/next-warehousing-solutions-front-end:$SHORT_SHA',
          ]
