import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useContext } from 'react'
import { GridView } from '../components/grid-view/grid-view'
import { MainLoader } from '../components/main-loader/main-loader'
import LoaderContext from '../services/loader'

const Articles: NextPage = () => {
	const context = useContext(LoaderContext)

	return (
		<>
			<Head>
				<title>Next Warehousing solutions.</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<button
				onClick={() => {
					context.show ? context.hideLoader() : context.showLoader()
				}}
			>
				toggle
			</button>

			<br />
			<br />
			<br />

			<div className="container-fluid">
				<GridView />
			</div>
		</>
	)
}

export default Articles
